CREATE DATABASE mmall CHARACTER SET 'utf8' COLLATE 'utf8_general_ci';#创建数据库
USE mmall;

##购物车
CREATE TABLE mmall_cart(
id INT(11) NOT NULL AUTO_INCREMENT,
user_id INT(11) NOT NULL COMMENT '用户id',
product_id INT(11) NOT NULL COMMENT '产品id',
quantity INT(11) NOT NULL COMMENT '数量',
checked INT(11) NOT NULL,
create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY (id),
KEY idx_user_id (user_id) USING BTREE
)ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '购物车';

##商品种类
CREATE TABLE mmall_category(
id INT(11) NOT NULL AUTO_INCREMENT,
parent_id INT(11) NOT NULL COMMENT '父类id',
NAME VARCHAR(32) NOT NULL COMMENT '名字',
STATUS TINYINT(2) NOT NULL COMMENT '状态',
sort_order INT(11) NOT NULL COMMENT '序号',
create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY (id)
)ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT '商品种类';

##订单物品
CREATE TABLE mmall_order_item(
id INT(11) NOT NULL AUTO_INCREMENT,
user_id INT(11) NOT NULL,
order_no BIGINT(20) NOT NULL COMMENT '订单号',
product_id INT(11) NOT NULL COMMENT '产品id',
product_name VARCHAR(32) NOT NULL COMMENT '产品名字',
product_image VARCHAR(255) NOT NULL COMMENT '产品图片',##varchar(n),n为实际的字符数，最多为(65535-1-2-4-30*3)/3=21812个
current_unit_price DECIMAL(19,4) NOT NULL COMMENT '当前单价',##decimal(p,d)精确数值，p表示有效位数,d表示小数点后多少位，价格一般取（19,4）
quantity INT(11) NOT NULL COMMENT '数量',
total_price DECIMAL(19,4) NOT NULL COMMENT '总价',
create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(id),
KEY idx_user_order_id (user_id,order_no)
)ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT '订单物品';

##订单
CREATE TABLE mmall_order(
id INT(11) NOT NULL AUTO_INCREMENT,
order_no BIGINT(20) NOT NULL COMMENT '订单号',
user_id INT(11) NOT NULL COMMENT '用户id',
shipping_id INT(11) NOT NULL COMMENT '物流号',
payment DECIMAL(19,4) NOT NULL COMMENT '付款',
payment_type INT(11) NOT NULL COMMENT '付款方式',
postage INT(11) NOT NULL COMMENT '邮费',
STATUS TINYINT(2) NOT NULL COMMENT '状态',
payment_time TIMESTAMP COMMENT '付款时间',
send_time TIMESTAMP COMMENT '邮寄时间',
end_time TIMESTAMP COMMENT '结束时间',
close_time TIMESTAMP COMMENT '关闭时间',
create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(id),
KEY idx_user_id (user_id)
)ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT '订单';

##支付信息
CREATE TABLE mmall_pay_info(
id INT(11) NOT NULL AUTO_INCREMENT,
user_id INT(11) NOT NULL,
order_no BIGINT(20) NOT NULL COMMENT '订单号',
pay_platform INT(11) NOT NULL COMMENT '支付平台',
platform_number VARCHAR(32) NOT NULL COMMENT '平台号',
platform_status VARCHAR(32) NOT NULL COMMENT '平台状态',
create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(id),
KEY idx_user_order_id (user_id,order_no)
)ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT '支付信息';

##产品信息
CREATE TABLE mmall_product(
id INT(11) NOT NULL AUTO_INCREMENT,
category_id INT(11) NOT NULL COMMENT '产品种类号',
NAME VARCHAR(20) NOT NULL COMMENT '产品名称',
subtitle VARCHAR(20) NOT NULL COMMENT '子名称',
main_image VARCHAR(255) NOT NULL COMMENT '主图片',
sub_images VARCHAR(255) NOT NULL COMMENT '子图片',
price DECIMAL(19,4) NOT NULL COMMENT '价格',
stock INT(11) NOT NULL COMMENT '储量',
STATUS TINYINT(2) NOT NULL COMMENT '状态',
create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(id)
)ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT '产品信息';

##物流信息
CREATE TABLE mmall_shipping(
id INT(11) NOT NULL AUTO_INCREMENT,
user_id INT(11) NOT NULL,
receiver_name VARCHAR(32) NOT NULL COMMENT '收件人姓名',
receiver_mobile VARCHAR(11) NOT NULL COMMENT '收件人手机号',
receiver_province VARCHAR(32) NOT NULL COMMENT '收件人省份',
receiver_city VARCHAR(32) NOT NULL COMMENT '收件人城市',
receiver_address VARCHAR(32) NOT NULL COMMENT '收件人地址',
receiver_zip VARCHAR(32) NOT NULL COMMENT '收件人zip',
create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(id)
)ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT '物流信息';

##用户信息
CREATE TABLE mmall_user(
id INT(11) NOT NULL AUTO_INCREMENT,
username VARCHAR(32) NOT NULL COMMENT '用户名',
PASSWORD VARCHAR(32) NOT NULL COMMENT '密码',
email VARCHAR(32) NOT NULL COMMENT '邮箱',
phone VARCHAR(32) NOT NULL COMMENT '手机号',
question VARCHAR(32) NOT NULL COMMENT '密码找回问题',
answer VARCHAR(32) NOT NULL COMMENT '密码找回答案',
role TINYINT(2) NOT NULL COMMENT '角色',
create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY(id)
)ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT '用户信息';




